name:                ishber
version:             0.1.0.0
github:              "githubuser/ishber"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ishber#readme>

dependencies:
- base >= 4.7 && < 5
- persistent
- persistent-postgresql
- persistent-template
- text
- monad-control
- monad-logger
- unliftio-core
- transformers
- esqueleto
- time
- servant
- aeson
- warp
- servant-server
- servant-client
- servant-options
- wai
- wai-make-assets
- wai-cors
- servant-auth
- servant-auth-server
- servant-auth-client
- wai-app-static
- bytestring
- file-embed
- pcre-heavy
- classy-prelude

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- GeneralizedNewtypeDeriving
- ConstraintKinds
- FlexibleContexts
- TemplateHaskell
- DataKinds
- TypeOperators
- TypeFamilies
- MultiParamTypeClasses
- GADTs
- RecordWildCards
- FlexibleInstances
- DerivingStrategies
- StandaloneDeriving
- UndecidableInstances
- DeriveGeneric

library:
  source-dirs: src

executables:
  ishber-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ishber

tests:
  ishber-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ishber
